version: '3.8'

services:
  rabbitmq:
    build: 
      context: .
      dockerfile: Dockerfile.rabbitmq
    container_name: rabbitmq-server
    hostname: rabbitserver
    ports:
      - "15672:15672"
      - "5672:5672"

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgreSQL
    container_name: postgres-server
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
